<a href="https://colab.research.google.com/github/hrbae/DRB_ML_Training/blob/main/2nd_day/D2_Matrix_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

리스트 생성하기

In [ ]:
row, column = 2, 3 
arr_2d = [[None] * column for i in range(row)] 
print(arr_2d)
# [[None, None, None], [None, None, None]]



[[None, None, None], [None, None, None]]


다차원 리스트 생성하기

In [ ]:
R=[[1, 2, 3],[4, 5, 6]]
print(R)
# [[1, 2, 3], [4, 5, 6]]

[[1, 2, 3], [4, 5, 6]]


numpy 배열 이용하기

In [ ]:
import numpy as np
# 0으로 초기화된 2차원 배열 생성 
arr_2d = np.zeros((2, 3)) 
print(arr_2d) 
# [[0. 0. 0.] # [0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
R = np.array([[0, 1, 2], [3, 4, 5]])
# [[0, 1, 2], [3, 4, 5]]
#print(R)
R

array([[0, 1, 2],
       [3, 4, 5]])

리스트들 간의 연산은?

In [ ]:
A = [[1,2],[3,4]]
B = [[3,4],[5,6]]
print(A*B)
print(A+B)

TypeError: ignored

Numpy array간의 연산


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,4],[5,6]])
print(A*B)
print(A+B)
print(np.dot(A,B))

[[ 3  8]
 [15 24]]
[[ 4  6]
 [ 8 10]]
[[13 16]
 [29 36]]


In [2]:
# Google drive를 마운트
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [3]:
!pwd

/content


In [4]:
%cd drive/MyDrive/Colab\ Notebooks/Data_Structures

/content/drive/MyDrive/Colab Notebooks/Data_Structures


**주피터 노트북 파일을 임포트하기 위해서 설치**

In [1]:
!pip install import_ipynb

  Created wheel for import-ipynb: filename=import_ipynb-0.1.3-py3-none-any.whl size=2975 sha256=cddc56a14ed6b6eacd6b21c37feb40ddfa41d8cc5faae5c4f877cb073be17620
  Stored in directory: /root/.cache/pip/wheels/b1/5e/dc/79780689896a056199b0b9f24471e3ee184fbd816df355d5f0
Successfully built import-ipynb


In [5]:
import import_ipynb

In [6]:
from DS_Class.Matrix_Class import Matrix_calculation

importing Jupyter notebook from /content/drive/MyDrive/Colab Notebooks/Data_Structures/DS_Class/Matrix_Class.ipynb


In [7]:
A=[[1,2],[3,4]]
B=[[5,6],[7,8]]

C=Matrix_calculation.matMulti(A,B)
D=Matrix_calculation.matAdd(A,B)
print(C)
print(D)

[[19, 22], [43, 50]]
[[6, 8], [10, 12]]


**행렬계산을 통해서 마코프 체인 계산**

In [9]:
def MarkovProcess(I, R, n):
    ret=I
    print("Initial sate:")
    for i in range(n):
        ret=Matrix_calculation.matMulti(ret, R)
        print("At time: ", i+1, "\t", ret )

In [10]:
R=[[0.7, 0.3],[0.1, 0.9]]
I = [[0.55, 0.45]]

MarkovProcess(I, R, 100)


Initial sate:
At time:  1 	 [[0.43, 0.5700000000000001]]
At time:  2 	 [[0.358, 0.6420000000000001]]
At time:  3 	 [[0.3148, 0.6852]]
At time:  4 	 [[0.28888, 0.71112]]
At time:  5 	 [[0.273328, 0.726672]]
At time:  6 	 [[0.2639968, 0.7360032000000001]]
At time:  7 	 [[0.25839808, 0.7416019200000001]]
At time:  8 	 [[0.255038848, 0.7449611520000001]]
At time:  9 	 [[0.2530233088, 0.7469766912000001]]
At time:  10 	 [[0.25181398528000004, 0.7481860147200001]]
At time:  11 	 [[0.251088391168, 0.7489116088320001]]
At time:  12 	 [[0.2506530347008, 0.7493469652992001]]
At time:  13 	 [[0.25039182082048, 0.74960817917952]]
At time:  14 	 [[0.25023509249228804, 0.7497649075077121]]
At time:  15 	 [[0.25014105549537285, 0.7498589445046273]]
At time:  16 	 [[0.25008463329722375, 0.7499153667027765]]
At time:  17 	 [[0.25005077997833425, 0.749949220021666]]
At time:  18 	 [[0.25003046798700057, 0.7499695320129997]]
At time:  19 	 [[0.25001828079220034, 0.7499817192077999]]
At time:  20 	 [[0.25