<a href="https://colab.research.google.com/github/hrbae/DRB_ML_Training/blob/main/2nd_day/D2_Matrix_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

리스트 생성하기

In [ ]:
row, column = 2, 3 
arr_2d = [[None] * column for i in range(row)] 
print(arr_2d)
# [[None, None, None], [None, None, None]]



[[None, None, None], [None, None, None]]


다차원 리스트 생성하기

In [ ]:
R=[[1, 2, 3],[4, 5, 6]]
print(R)
# [[1, 2, 3], [4, 5, 6]]

[[1, 2, 3], [4, 5, 6]]


numpy 배열 이용하기

In [ ]:
import numpy as np
# 0으로 초기화된 2차원 배열 생성 
arr_2d = np.zeros((2, 3)) 
print(arr_2d) 
# [[0. 0. 0.] # [0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
R = np.array([[0, 1, 2], [3, 4, 5]])
# [[0, 1, 2], [3, 4, 5]]
#print(R)
R

array([[0, 1, 2],
       [3, 4, 5]])

리스트들 간의 연산은?

In [ ]:
A = [[1,2],[3,4]]
B = [[3,4],[5,6]]
print(A*B)
print(A+B)

TypeError: ignored

Numpy array간의 연산


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,4],[5,6]])
print(A*B)
print(A+B)
print(np.dot(A,B))

[[ 3  8]
 [15 24]]
[[ 4  6]
 [ 8 10]]
[[13 16]
 [29 36]]


In [ ]:
# Google drive를 마운트
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
!pwd

/content


In [ ]:
%cd drive/MyDrive/Colab\ Notebooks/Data_Structures

/content/drive/MyDrive/Colab Notebooks/Data_Structures


**주피터 노트북 파일을 임포트하기 위해서 설치**

In [ ]:
!pip install import_ipynb

In [ ]:
import import_ipynb

In [ ]:
from DS_Class.Matrix_Class import Matrix_calculation

importing Jupyter notebook from /content/drive/MyDrive/Colab Notebooks/Data_Structures/DS_Class/Matrix_Class.ipynb


In [ ]:
A=[[1,2],[3,4]]
B=[[5,6],[7,8]]

C=Matrix_calculation.matMulti(A,B)
D=Matrix_calculation.matAdd(A,B)
print(C)
print(D)

[[19, 22], [43, 50]]
[[6, 8], [10, 12]]
