In [1]:
import numpy as np

## Array

### Array 생성

In [5]:
a = np.array([1,2,3])
print(a) #array의 값 출력
print(type(a)) #array의 유형 체크

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
print(a.shape) # array의 차원 확인
print(a[0],a[1],a[2]) #인덱스를 이용한 array내 값 접근
a[2]=7 # 인덱스를 이용한 array 값 변경 가능
print(a)

(3,)
1 2 3
[1 2 7]


### 다차원 Array 생성

In [11]:
[[1,2,3],[4,5,6]]

[[1, 2, 3], [4, 5, 6]]

In [12]:
b = np.array([[1,2,3],[4,5,6]]) #다차원 리스트로 다차원 array 생성 가능
print(b)

[[1 2 3]
 [4 5 6]]


In [15]:
print(b.shape) #다차원 array의 모양 확인
print(b[0][0])
print(b[0,0]) # numpy에서 추가로 허용하는 문법
print(b[1][1])
print(b[1,1])

(2, 3)
1
1
5
5


### numpy 메소드를 이용한 생성

In [17]:
a = np.zeros((2,2)) #0으로 채워넣기
print(a)

[[0. 0.]
 [0. 0.]]


In [18]:
b = np.ones((2,3)) #1로 채워넣기
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
c = np.full((3,3),7) # 같은 값으로 채워넣기, api 확인!
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [21]:
e = np.random.random((2,2)) #난수 생성
print(e)

[[0.04415978 0.38611699]
 [0.52051103 0.75647403]]


In [22]:
np.arange(4)

array([0, 1, 2, 3])

In [23]:
np.arange(1,7,2)

array([1, 3, 5])

In [25]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### numpy 객체의 차원과 갯수 확인

In [27]:
a.shape

(2, 2)

In [30]:
a.size

4

### Reshaping (차원 바꾸기)

In [32]:
x = np.arange(12)
print(x)
print(x.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [33]:
y = x.reshape(2,6)
print(y)
print(y.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)


In [35]:
print(x.reshape(3,4))
print(x.reshape(3,4).shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [38]:
x = np.ones((2,4)) 
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
x.reshape(4,2) ## 다차원 array의 reshaping도 가능합니다.

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])