In [2]:
import numpy as np

## Array Indexing(배열 인덱싱)

In [6]:
a = np.array([1,2,3,4])
print(a[:2])
print(a[1:3])

[1 2]
[2 3]


In [5]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 다차원 array의 인덱싱

In [7]:
c = b[:2,1:3] # 행: 0,1, 열: 1,2
print(c) 

[[2 3]
 [6 7]]


### Array의 원본 참조

In [11]:
print(b, b[0,1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 2


In [13]:
c[0,0]=77
print(c)
print(b) # c가 b를 참조하고 있으므로, c의 값도 바뀐것을 확인할 수 있다.

[[77  3]
 [ 6  7]]
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 행열 추려내기

In [14]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
row1=b[0,:] #1행
row2=b[1,:] #2행
row3=b[2,:] #3행
print(row1)
print(row2)
print(row3)
print(row1.shape)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
(4,)


In [29]:
col1=b[:,0] #1열
col2=b[:,1] #2열
col3=b[:,2] #3열
print(col1, col2, col3)
print(col1.shape)

[1 5 9] [ 2  6 10] [ 3  7 11]
(3,)


In [31]:
row1=b[0:1,:]
print(row1) #다차원 array로 생성됨
print(row1.shape) #2차원으로 생성됨에 유의

[[1 2 3 4]]
(1, 4)


In [32]:
col2 = b[:,[1]]
print(col2) # 다차원 array로 생성됨
print(col2.shape) #2차원으로 생성됨에 유의

[[ 2]
 [ 6]
 [10]]
(3, 1)


###  행열의 순서 바꾸기

In [40]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
print(a[[0,1,2],:]) #a와 같은 결과
print(a[[0,2,1],:]) #1행, 3행, 2행으로 바뀜

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [5 6]
 [3 4]]


In [43]:
print(a[:,[1,0]]) # 2열, 1열 순으로 바뀜

[[2 1]
 [4 3]
 [6 5]]


In [44]:
print(a[:,[1,1]]) # 같은 열로 덮어씌워짐

[[2 2]
 [4 4]
 [6 6]]


In [45]:
print(a[[0,1,2],[0,1,0]]) 
print(np.array([a[0,0],a[1,1],a[2,0]]))

[1 4 5]
[1 4 5]


In [37]:
print(a[[0,0],[1,1]]) 

[2 2]


In [38]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Boolean Indexing

In [47]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [48]:
print(a>2)

[[False False]
 [ True  True]
 [ True  True]]


In [49]:
a[a>2]

array([3, 4, 5, 6])

In [50]:
a[a>2].size

4

In [55]:
np.random.seed(3)
ra = np.random.random(25)
ra[(ra>0.3) & (ra<0.5)] #조건이 여러개일때도 가능 (and대신 &, |를 사용함에 유의)

array([0.44080984, 0.45683322, 0.4151012 , 0.44045372])