In [1]:
import numpy as np

### numpy 연산

In [7]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [8]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [9]:
print(x//y)
print(x**y)
print(x%y)

[0 0 0 0]
[    1    64  2187 65536]
[1 2 3 4]


### 취합연산

In [10]:
print(np.sum(x))
print(np.prod(x))
print(np.mean(x))
print(np.std(x))
print(np.min(x))
print(np.max(x))
print(np.median(x))

10
24
2.5
1.118033988749895
1
4
2.5


### 다차원 array 연산

In [11]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [12]:
print(x+y) ## 다차원 연산시 element별 연산 수행
print(x-y)
print(x*y)
print(x/y)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [13]:
print(x//y)
print(x**y)
print(x%y)

[[0 0]
 [0 0]]
[[    1    64]
 [ 2187 65536]]
[[1 2]
 [3 4]]


In [14]:
x.dot(y) ## 행렬연산

array([[19, 22],
       [43, 50]])

In [15]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

### 다차원 array 취합연산

In [20]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [16]:
print(np.sum(x))
print(np.prod(x))
print(np.mean(x))
print(np.std(x))
print(np.min(x))
print(np.max(x))
print(np.median(x))

10
24
2.5
1.118033988749895
1
4
2.5


In [19]:
print(np.sum(x,axis=0)) #행 방향으로 연산 수행
print(np.prod(x,axis=0))
print(np.mean(x,axis=0))
print(np.std(x,axis=0))
print(np.min(x,axis=0))
print(np.max(x,axis=0))
print(np.median(x,axis=0))

[4 6]
[3 8]
[2. 3.]
[1. 1.]
[1 2]
[3 4]
[2. 3.]


In [21]:
print(np.sum(x,axis=1)) #열 방향으로 연산 수행
print(np.prod(x,axis=1))
print(np.mean(x,axis=1))
print(np.std(x,axis=1))
print(np.min(x,axis=1))
print(np.max(x,axis=1))
print(np.median(x,axis=1))

[3 7]
[ 2 12]
[1.5 3.5]
[0.5 0.5]
[1 3]
[2 4]
[1.5 3.5]


### Broadcasting

In [24]:
a = np.array([1,2,3,4])
print(a + 3)
print(a * 3)

[4 5 6 7]
[ 3  6  9 12]


In [25]:
b = np.array([[1,2,3],[4,5,6]])
print(b+3) 
print(b*3) 

[[4 5 6]
 [7 8 9]]
[[ 3  6  9]
 [12 15 18]]


In [27]:
c = np.array([7,8,9])
print(b)
print(b+c)
print(b*c)

[[1 2 3]
 [4 5 6]]
[[ 8 10 12]
 [11 13 15]]
[[ 7 16 27]
 [28 40 54]]


In [29]:
d = np.array([7,8]).reshape(2,1)
d

array([[7],
       [8]])

In [30]:
print(b+d)

[[ 8  9 10]
 [12 13 14]]
